name: AntiGriefSystem
version: '${version}'
main: ru.antigrief.AntiGriefSystem
api-version: '1.21'
authors: [Antag0nis1]
description: A plugin to protect servers with a trust system and item restrictions.
commands:
  ags:
    description: Main command for AntiGriefSystem
    usage: /ags <subcommand>
    permission: ags.admin
  feedback:
    description: Send feedback to developers
    usage: /feedback <subcommand>
    permission: plugin.feedback.send
permissions:
  ags.admin:
    description: Allows full control of AntiGriefSystem
    default: op
  plugin.feedback.send:
    description: Allow sending feedback
    default: true
  plugin.feedback.history:
    description: Allow viewing feedback history
    default: true
  ags.alerts:
    description: Receive in-game cheat/restriction alerts
    default: op
libraries:
  - org.xerial:sqlite-jdbc:3.46.0.0
  - com.zaxxer:HikariCP:5.1.0
  - org.slf4j:slf4j-simple:2.0.9
